Added style to FAQ page
robogyan-adgitm/robogyan-adgitm.github.io pull request #47
Opened 2022-10-06 21:26 UTC by Akshay-21

Hey Hi @robogyan-adgitm i Added style for FAQ page. I have created PR kindly check it and merge.
Thank You!

2022-10-07 10:52 UTC, robogyan-adgitm requested changes

2022-10-07 10:52 UTC, robogyan-adgitm commented on dist/css/main.scss
> +                a {
All the changes in this page is spam

2022-10-07 10:52 UTC, robogyan-adgitm commented on faq.html
> +  <!-- ================================================================== -->
No personal info in code allowed

2022-10-07 16:45 UTC, Akshay-21 commented on dist/css/main.scss
> +                a {
Ok i will check this issue.

2022-10-07 16:45 UTC, Akshay-21 commented on faq.html
> +  <!-- ================================================================== -->
This one also i will check.

2022-10-07 16:48 UTC, Akshay-21 commented
Hey Hi @robogyan-adgitm after this comment i will see this and what do i need to do for this issue.

2022-10-07 18:47 UTC, robogyan-adgitm commented
Just resolve these two things and recreate the PR

2022-10-07 20:45 UTC, Akshay-21 commented
> Just resolve these two things and recreate the PR

Hi @robogyan-adgitm, i have removed unused file and code and personal info, i have updated FAQ Accordion using smooth design with theme matching.

Please kindly check this.

Thank You!

![image](https://user-images.githubusercontent.com/32409386/194649756-0ca74e6c-3d6f-4d3f-8bfb-17ae3e93e1b4.png)

2022-10-07 20:46 UTC, Akshay-21 commented on dist/css/main.scss
> +                a {
Removed these things.

2022-10-07 20:47 UTC, Akshay-21 commented on faq.html
> +  <!-- ================================================================== -->
Removed Personal info.

2022-10-07 21:29 UTC, robogyan-adgitm approved these changes
Good

2022-10-07 21:33 UTC, robogyan-adgitm commented
Not be merging this as from the design it's not clear that the unexpanded questions could be expanded. And for now current UI for the FAQs is better. Marked as hacktoberfest-accepted though as it is a good enough contribution to be worked on later.

2022-10-08 06:34 UTC, Akshay-21 commented
> Not be merging this as from the design it's not clear that the unexpanded questions could be expanded. And for now current UI for the FAQs is better. Marked as hacktoberfest-accepted though as it is a good enough contribution to be worked on later.

Thank You! For Accepting the PR.

2022-10-09 11:40 UTC, closed without merging