My new branch
robogyan-adgitm/robogyan-adgitm.github.io pull request #66
Opened 2022-10-08 13:27 UTC by Madhur1808

link of google form and instagram handle will open in new tab for better user experience.

2022-10-08 13:58 UTC, robogyan-adgitm commented on contributors/contributorsList.js
> +    fullname: "Ashish",
Name?

2022-10-08 15:32 UTC, Madhur1808 commented on contributors/contributorsList.js
> +    fullname: "Ashish",
shutikshan madhur

2022-10-08 16:28 UTC, robogyan-adgitm requested changes
Add your name in the list bruh :rofl:

2022-10-09 15:27 UTC, robogyan-adgitm commented
resolve conflicts @Madhur1808

2022-10-10 13:40 UTC, robogyan-adgitm approved these changes

2022-10-10 13:40 UTC, merged